### ISSUE TITLE
A new tool for RNA modification analysis 

### ISSUE THREAD

**Issue by q1134269149** [GoekeLab/awesome-nanopore#14]
Hi,

A new tool, DENA (https://github.com/weir12/DENA) (Qin, H., Ou, L., Gao, J. et al. DENA: training an authentic neural network model using Nanopore sequencing data of Arabidopsis transcripts for detection and quantification of N6-methyladenosine on RNA. Genome Biol 23, 25 (2022). https://doi.org/10.1186/s13059-021-02598-3), that was developed by our group, can be used  for RNA modification analysis. Perhaps you can add it to the corresponding list.

Best,

Hang

**Comment by yuukiiwa** [comment]
Hi @q1134269149,

Thanks for the contribution! I have merged the Pull Request with DENA into the list.

Best wishes,
Yuk Kei
